# Introduction

In [2]:
import torch, torch_directml
import numpy as np
dml = torch_directml.device()
print(torch_directml.device_name(0))

AMD Radeon(TM) 860M Graphics


In [2]:
torch.__version__

'2.4.1+cpu'

## Scalar

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

### Get number back from scalar

In [6]:
scalar.item()

7

## Vector

In [16]:
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

### Number of square bracket sets is ndim

In [10]:
vector.ndim

1

### Shape is count of elements

In [11]:
vector.shape

torch.Size([4])

# Matrix

In [12]:
mx = torch.arange(1, 10).reshape(3, 3)
mx

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
mx.ndim

2

In [14]:
mx.shape

torch.Size([3, 3])

# Tensor

In [17]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
TENSOR[0][1]

tensor([4, 5, 6])

In [23]:
TENSOR[0][1][2]

tensor(6)

# Randome Tensors

Neural networks start with random numbers and then keep on changing its weights 

In [31]:
random_tensor = torch.rand(1,3, 4)
random_tensor

tensor([[[0.9964, 0.8916, 0.3395, 0.2978],
         [0.1653, 0.6824, 0.3328, 0.3349],
         [0.0622, 0.5463, 0.7706, 0.9952]]])

In [32]:
random_tensor.ndim

3

In [33]:
random_tensor.shape

torch.Size([1, 3, 4])

# Zeros and ones

In [36]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
ones = torch.ones((3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

# Range

In [4]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Like

In [5]:
zeros = torch.zeros_like(one_to_ten)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor data types

In [11]:
ftensor = torch.tensor([1.0, 2.0, 3.0])

In [12]:
ftensor.dtype

torch.float32

In [13]:
ftensor_16 = ftensor.to(torch.float16)

In [14]:
ftensor_16.dtype

torch.float16

In [19]:
f16 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
f32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)


In [20]:
f16*f32

tensor([1., 4., 9.])

# Tensor attributes

In [21]:
rt = torch.rand(3,4,5)

In [22]:
rt.shape

torch.Size([3, 4, 5])

In [24]:
rt.size()

torch.Size([3, 4, 5])

In [25]:
rt.ndim

3

In [26]:
rt.device

device(type='cpu')

# Tensor Manipulations

In [29]:
tr = torch.tensor([1, 2, 3])
tr

tensor([1, 2, 3])

In [31]:
tr + 10

tensor([11, 12, 13])

In [32]:
tr * 10

tensor([10, 20, 30])

In [33]:
tr-10

tensor([-9, -8, -7])

# Two ways of multiplication
![alt text](image.png)

In [35]:
tr = torch.tensor([1, 2, 3])
tr

tensor([1, 2, 3])

In [36]:
tr * tr

tensor([1, 4, 9])

In [38]:
torch.matmul(tr,tr)

tensor(14)

In [54]:
tr = torch.arange(1,10001)

In [55]:
%%time
value = 0
for i in range(len(tr)):
    value += tr[i] * tr[i]
print(value)


tensor(333383335000)
CPU times: total: 62.5 ms
Wall time: 56 ms


In [56]:
%%time
value = torch.matmul(tr,tr)
print(value)

tensor(333383335000)
CPU times: total: 0 ns
Wall time: 1 ms


In [62]:
m1 = torch.randint(0, 10, (3, 4)) 
m2 = torch.randint(0, 10, (4, 2))

In [61]:
m1

tensor([[2, 6, 3, 7],
        [8, 7, 7, 1],
        [0, 2, 1, 6]])

In [63]:
m2

tensor([[2, 7],
        [5, 6],
        [4, 0],
        [7, 0]])

In [64]:
torch.matmul(m1,m2)

tensor([[67, 79],
        [57, 55],
        [90, 24]])

# Aggregation of tensors

In [80]:
m1 = torch.arange(0, 101, 10)

In [81]:
m1

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [86]:
m1.shape

torch.Size([11])

In [82]:
m1.dtype

torch.int64

In [84]:
m1.min(), m1.max(), torch.mean(m1.to(dtype=torch.float32)), m1.sum()

(tensor(0), tensor(100), tensor(50.), tensor(550))

## Find position of min or max

In [85]:
m1.argmax()

tensor(10)

# Reshaping, stacting, sqeezing and unsqueezing 

In [3]:
t1 = torch.randint(1,20,(10,2))

In [4]:
t1.shape

torch.Size([10, 2])

In [5]:
t1

tensor([[17, 11],
        [ 5, 17],
        [19, 11],
        [ 2,  5],
        [16, 13],
        [ 8,  2],
        [ 3, 17],
        [13, 13],
        [13,  5],
        [14,  7]])

In [90]:
t2 = t1.reshape((5,4))
t2

tensor([[11,  8, 18,  2],
        [15, 11,  5,  9],
        [14,  4, 16, 18],
        [ 1, 10, 16,  3],
        [ 3, 15,  9,  2]])

In [92]:
t3 = t1.reshape((5,5))
t3

RuntimeError: shape '[5, 5]' is invalid for input of size 20

In [93]:
v1 = t1.view(4,5)
v1

tensor([[11,  8, 18,  2, 15],
        [11,  5,  9, 14,  4],
        [16, 18,  1, 10, 16],
        [ 3,  3, 15,  9,  2]])

In [95]:
t1[0][0] = 100

In [96]:
t1

tensor([[100,   8],
        [ 18,   2],
        [ 15,  11],
        [  5,   9],
        [ 14,   4],
        [ 16,  18],
        [  1,  10],
        [ 16,   3],
        [  3,  15],
        [  9,   2]])

In [97]:
v1

tensor([[100,   8,  18,   2,  15],
        [ 11,   5,   9,  14,   4],
        [ 16,  18,   1,  10,  16],
        [  3,   3,  15,   9,   2]])

In [98]:
t2

tensor([[100,   8,  18,   2],
        [ 15,  11,   5,   9],
        [ 14,   4,  16,  18],
        [  1,  10,  16,   3],
        [  3,  15,   9,   2]])

In [100]:
v1 = torch.arange(1,4)
v1

tensor([1, 2, 3])

In [114]:
x = torch.tensor([[[1, 2, 3], [4, 5, 6]]])

In [115]:
x

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [117]:
x.shape

torch.Size([1, 2, 3])

In [118]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [120]:
x.squeeze().shape

torch.Size([2, 3])

In [121]:
y = x.squeeze()

In [126]:
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [123]:
y.shape

torch.Size([2, 3])

In [139]:
y.ndim

2

In [140]:
y.unsqueeze(dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [141]:
y.unsqueeze(dim=0).shape

torch.Size([1, 2, 3])

In [142]:
y.unsqueeze(dim=0).ndim

3

In [138]:
y.unsqueeze(dim=1)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [136]:
y.unsqueeze(dim=2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [137]:
y.unsqueeze(dim=2).shape

torch.Size([2, 3, 1])

In [149]:
x = torch.zeros(1, 3, 2, 5)
x

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])

In [143]:
x = torch.zeros(1, 3, 1, 5)
x.squeeze().shape     # (3, 5)        — removes ALL size-1 dims
x.squeeze(0).shape    # (3, 1, 5)     — removes only dim 0
x.squeeze(2).shape    # (1, 3, 5)     — removes only dim 2
x.squeeze(1).shape    # (1, 3, 1, 5)  — dim 1 is size 3, not 1 → no change

torch.Size([1, 3, 1, 5])

# permute

In [6]:
x_original = torch.rand(size=(224, 224, 3))

In [9]:
x_original.shape

torch.Size([224, 224, 3])

### Permute the tensor to rearrange the axis or dim order

In [10]:
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [13]:
x_permuted[0,0,0] = -1

In [14]:
x_permuted

tensor([[[-1.0000,  0.2440,  0.4685,  ...,  0.4868,  0.5316,  0.3489],
         [ 0.7792,  0.6719,  0.4351,  ...,  0.3096,  0.6716,  0.7113],
         [ 0.3774,  0.8883,  0.6233,  ...,  0.7162,  0.6920,  0.2240],
         ...,
         [ 0.5193,  0.0188,  0.7041,  ...,  0.3328,  0.8733,  0.3106],
         [ 0.3912,  0.4767,  0.9826,  ...,  0.1041,  0.7306,  0.4817],
         [ 0.1919,  0.5541,  0.1478,  ...,  0.7497,  0.1829,  0.5390]],

        [[ 0.9984,  0.4750,  0.3501,  ...,  0.0625,  0.9687,  0.1065],
         [ 0.6384,  0.6027,  0.2723,  ...,  0.7182,  0.3999,  0.6883],
         [ 0.6697,  0.0147,  0.7207,  ...,  0.2233,  0.3929,  0.6260],
         ...,
         [ 0.3244,  0.9900,  0.7481,  ...,  0.3774,  0.9700,  0.7169],
         [ 0.7973,  0.6962,  0.5338,  ...,  0.6702,  0.8324,  0.6649],
         [ 0.1089,  0.8256,  0.9320,  ...,  0.4982,  0.8891,  0.9968]],

        [[ 0.5911,  0.2744,  0.7542,  ...,  0.0688,  0.9251,  0.2766],
         [ 0.3563,  0.0897,  0.8917,  ...,  0

In [15]:
x_original

tensor([[[-1.0000,  0.9984,  0.5911],
         [ 0.2440,  0.4750,  0.2744],
         [ 0.4685,  0.3501,  0.7542],
         ...,
         [ 0.4868,  0.0625,  0.0688],
         [ 0.5316,  0.9687,  0.9251],
         [ 0.3489,  0.1065,  0.2766]],

        [[ 0.7792,  0.6384,  0.3563],
         [ 0.6719,  0.6027,  0.0897],
         [ 0.4351,  0.2723,  0.8917],
         ...,
         [ 0.3096,  0.7182,  0.3787],
         [ 0.6716,  0.3999,  0.3102],
         [ 0.7113,  0.6883,  0.6167]],

        [[ 0.3774,  0.6697,  0.1669],
         [ 0.8883,  0.0147,  0.4402],
         [ 0.6233,  0.7207,  0.1172],
         ...,
         [ 0.7162,  0.2233,  0.6424],
         [ 0.6920,  0.3929,  0.5441],
         [ 0.2240,  0.6260,  0.5379]],

        ...,

        [[ 0.5193,  0.3244,  0.3460],
         [ 0.0188,  0.9900,  0.4114],
         [ 0.7041,  0.7481,  0.2283],
         ...,
         [ 0.3328,  0.3774,  0.1924],
         [ 0.8733,  0.9700,  0.2082],
         [ 0.3106,  0.7169,  0.7683]],

        [[

# Indexing

In [3]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0] 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
x[0][0] , x[0][2][2]

(tensor([1, 2, 3]), tensor(9))

In [28]:
x[:,0]

tensor([[1, 2, 3]])

In [9]:
x[:,:, 1]

tensor([[2, 5, 8]])

In [30]:
x[:,1,1]

tensor([5])

# Pytorch and numpy

### Note np to torch array float is 64 whereas its 32 by default

In [18]:
arr = np.array([1.0, 3.0, 3.0])
tensor = torch.from_numpy(arr)
arr, tensor

(array([1., 3., 3.]), tensor([1., 3., 3.], dtype=torch.float64))

In [16]:
t1 = torch.tensor([1.0,3.0,5.0  ])
t1, t1.dtype, t1.device

(tensor([1., 3., 5.]), torch.float32, device(type='cpu'))

# Random tensors

In [3]:
r1 = torch.rand(3,4, device=dml)
r2 = torch.rand(3,4, device=dml)


In [4]:
r1, r2

(tensor([[0.8897, 0.6751, 0.7733, 0.5202],
         [0.9447, 0.9674, 0.0717, 0.0322],
         [0.3541, 0.4115, 0.6114, 0.0161]], device='privateuseone:0'),
 tensor([[0.5542, 0.6245, 0.6675, 0.4405],
         [0.8241, 0.2345, 0.1185, 0.6383],
         [0.7686, 0.2142, 0.8317, 0.7830]], device='privateuseone:0'))

In [5]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [8]:
torch.manual_seed(RANDOM_SEED)
r1 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
r2 = torch.rand(3,4)
r1, r2, r1==r2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

# GPU for faster computation

In [4]:

import torch
import torch_directml

# 1. Get the AMD GPU as a DirectML device
device = torch_directml.device()
print("Using device:", device)   # e.g. privateuseone:0

# 2. Move tensors to the device
#    For x @ y the inner dims must match: (100 x 255) @ (255 x 50)
x = torch.randn(100, 255).to(device)
y = torch.randn(255, 50).to(device)




Using device: privateuseone:0


In [6]:
%%time
# 3. Operation runs on the AMD GPU
z = x @ y
print("Result shape:", z.shape)   # (100, 50)
print("Tensor is on:", z.device)


Result shape: torch.Size([100, 50])
Tensor is on: privateuseone:0
CPU times: total: 0 ns
Wall time: 1.01 ms
